### ISSUE TITLE
Opening the browser makes the bar disappear and the dwm stops responding

### ISSUE THREAD

**Issue by pizza-eater** [saloniamatteo/dwm#2]
The problem started when I tried to open discord in opera. When this happens, the dwm immediately stops responding. If I'm just surfing in a browser, for example, in firefox, then this problem can occur at any time, and I don't know the exact trigger except for the case with discord

**Comment by saloniamatteo** [comment]
Don't know what the cause of this issue is, because I don't use Opera, nor Discord.

Perhaps your system may be running out of resources when you open Discord (low RAM? CPU is throttling?)

When an issue like this arises (program stops working, as in it freezes), then it's likely resources running low.

**Comment by lernant** [comment]
Interesting. I commented out the following lines in .xsession file, and the problem disappeared. 
`#feh --bg-scale ~/Images/bg.jpe`
`#compton &`
What can this be related to?

**Comment by saloniamatteo** [comment]
You're setting the background with `feh`, I don't see how that could cause any issues.
With `compton` (now renamed to `picom`), you're launching a compositor. Perhaps the compositor is the issue?

**Comment by saloniamatteo** [comment]
It'd be useful if you posted the following info:
1. Distro & Currently used Kernel
2. Version of `compton`/`picom`
